apiVersion: apps/v1
kind: Deployment
metadata:
  name: srepaul-deployment
  labels:
    app: srepaul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srepaul
  template:
    metadata:
      labels:
        app: srepaul
    spec:
      containers:
      - name: srepaul
        image: paulrobu/srepaul
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: srepaul-service
spec:
  type: NodePort
  selector:
    app: srepaul
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31981
